### ISSUE TITLE
lots of empty newline when redirected to log files

### ISSUE THREAD

**Issue by xgdgsc** [cloud-oak/ProgressBars.jl#15]
I get about a hundred empty newlines between progesses when I redirect progressbar result to file. In the terminal it looks ok with consecutive lines.  Don' know if there could be any improvements regarding this.  I have some logs using @info inside the loop, but shouldn' t be empty newlines.

```
99.95%┣█████████████████████████████████████████████████████████▉┫ 3846/3848 02:57<00:00, 21.72 it/s]



































































































100.00%┣████████████████████████████████████████████████████████▉┫ 3848/3848 02:57<00:00, 21.73 it/s]
```

**Comment by cloud-oak** [comment]
Hi, thanks for bringing up this issue. Indeed, this was an error in ProgressBars.jl.

Progressbars.jl works by resetting the terminal cursor to the beginning of the line by printing the special character `\r`. AFAIK, on MacOS this is equivalent to a newline character when it appears in a text file. The old code was printing way too many of these characters, leading to the behavior observed by you.

Ideally, I would like to implement a "log-file mode", where printing is done only once, so that log-files aren't littered with hundreds of progress bars.

**Comment by cloud-oak** [comment]
I've released a new package version (v0.5.0). Could you check whether it fixes your issue?

Cheers, Konrad

**Comment by xgdgsc** [comment]
Thanks. It works. Though the order of progress and @info is weird(my @info would come in the middle with large blocks and then large progressbar blocks, unlike in python tqdm it would follow the order of progress->info in between). It is good enough for me.

**Comment by cloud-oak** [comment]
Closing this for now. However, I'd like to investigate further into this at some point in the future...
