### ISSUE TITLE
add to official registry

### ISSUE THREAD

**Issue by xgdgsc** [cloud-oak/ProgressBars.jl#4]
Please add this to official registry for easier installing.

**Comment by cloud-oak** [comment]
The request for official release is now open at JuliaLang/METADATA.jl#19791, let's hope it gets approved.

**Comment by Wikunia** [comment]
I would love to use this package in one of my programs. Are you considering to rename the package as mentioned in the discussion you posted?

**Comment by cloud-oak** [comment]
@Wikunia Sure, any suggestions for a sensible name?

Looking at the Julia package naming guidelines, I'd probably name it `ProgressBars.jl`, and change the name of the `tqdm` class to `ProgressBar`.

However, I'd be happier with a shorter name, so that the `for i in tqdm(iter)` wouldn't become a full blown `for i in ProgressBar(iter)`... Let me know if you have any ideas!

**Comment by Wikunia** [comment]
I like `progress(iter)` or shorter `ttc(iter)` for Time to completion.
It could be just a synonym so both could work. I think the important part is that it's easy to find the package so I think the package should be called `ProgressBar.jl` and then the function can be called something shorter.

**Comment by xgdgsc** [comment]
Package name could be ProgressBar. Maybe you can support both tqdm and ProgressBar in the package. I like the old tqdm name.

**Comment by cloud-oak** [comment]
Alright, I'll set up a PR

**Comment by cloud-oak** [comment]
Here goes JuliaLang/Metadata.jl#22512 :crossed_fingers:

**Comment by cloud-oak** [comment]
Good news everybody! ProgressBars.jl is now available from the official registry!
