### ISSUE TITLE
Customize update period

### ISSUE THREAD

**Issue by rwhebell** [cloud-oak/ProgressBars.jl#41]
In the case of a loop with many iterations (>10^8), where each iteration is very fast, it would be great to have a way to customize how often the progress bar updates. For example, every 100 iterations. 

If this is already possible, it doesn't appear to be documented.

**Comment by khdlr** [comment]
Hi Riley, the current behaviour is to wait at least 50ms between progress bar updates in order to prevent console IO from slowing down the actual work too much. Admittedly, this is hardcoded in the current version. Therefore I guess right now is a great time to dig further into that :smile: 

Would the possibility of adjusting the delay between pbar updates be enough for your needs or do you need the updates to happen exactly on every n-th iteration?

**Comment by rwhebell** [comment]
Just an interface for the user to specify that delay would be handy, I think. 

(appreciate the package, by the way -- it puts my mind at ease to see iterations visually)

**Comment by khdlr** [comment]
Hi there, this is now implemented in the brand-new [v1.2.0 release](https://github.com/cloud-oak/ProgressBars.jl/releases/tag/v1.2.0) via the `printing_delay` parameter. Documented here: https://github.com/cloud-oak/ProgressBars.jl#printing-delay
